Traceback (most recent call last):
  File "train_model.py", line 136, in <module>
    load_path = load_path, save_path = save_path)
  File "/home/lamsade/lgnecco/risk/pyLux/core/model.py", line 410, in train_model
    state_dict = load_dict(load_path, device, encoding = 'latin1')
  File "/home/lamsade/lgnecco/risk/pyLux/core/model.py", line 48, in load_dict
    state_dict = torch.load(f, map_location=device, encoding = encoding)
  File "/home/lamsade/lgnecco/.local/lib/python3.7/site-packages/torch/serialization.py", line 580, in load
    if _is_zipfile(opened_file):
  File "/home/lamsade/lgnecco/.local/lib/python3.7/site-packages/torch/serialization.py", line 57, in _is_zipfile
    byte = f.read(1)
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
Done
Traceback (most recent call last):
  File "expert_iteration_external.py", line 47, in <module>
    inputs = misc.read_json(args.inputs)
  File "/home/lamsade/lgnecco/risk/pyLux/core/misc.py", line 26, in read_json
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../support/exp_iter_inputs/exp_iter_inputs_small.json'
Done
Traceback (most recent call last):
  File "expert_iteration_external.py", line 47, in <module>
    inputs = misc.read_json(args.inputs)
  File "/home/lamsade/lgnecco/risk/pyLux/core/misc.py", line 26, in read_json
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../support/exp_iter_inputs/exp_iter_inputs_small.json'
Done
